### ISSUE TITLE
lect1

### ISSUE THREAD

**Issue by SaraFerrari1999** [unitn-drive/networking-2#1]

**Comment by mfranzil** [comment]
Non c'è scritto nulla nell'issue, l'hai risolta suppongo?

**Comment by SaraFerrari1999** [comment]
Si scusami volevo cancellarla ma non ci sono riuscita a quanto sembra ,non
sono molto pratica con github. Stavo provando ad aggiungere due repository
e ci sono riuscita e all inizio pensavo si aggiungessero con l issues.

Il Mer 28 Set 2022, 10:18 Matteo Franzil ***@***.***> ha
scritto:

**Comment by mfranzil** [comment]
Tranquilla allora. La segno come risolta.
